# Generated by Django 3.2.15 on 2023-06-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(help_text='Добавьте подробное описание рецепта', verbose_name='Описание рецепта'),
        ),
    ]
