# Generated by Django 3.2.15 on 2023-06-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(help_text='Добавьте подробное описание рецепта', unique=True, verbose_name='Описание рецепта'),
        ),
    ]
